return {
  -- "nvim-neo-tree/neo-tree.nvim",
  -- cmd = "Neotree",
  -- priority = 1000,
  -- dependencies = {
  --   "nvim-lua/plenary.nvim",
  --   "nvim-tree/nvim-web-devicons",
  --   "MunifTanjim/nui.nvim",
  -- },
  -- keys = {
  --   {
  --     "<leader>e",
  --     function()
  --       require("neo-tree.command").execute({ reveal = true, toggle = true, dir = vim.loop.cwd(), position = "current" })
  --     end,
  --     desc = "Explorer NeoTree (cwd)",
  --   },
  --   {
  --     "<leader>ge",
  --     function()
  --       require("neo-tree.command").execute({ source = "git_status", reveal = true, toggle = true, position = "current" })
  --     end,
  --     desc = "Git explorer",
  --   },
  --   {
  --     "<leader>be",
  --     function()
  --       require("neo-tree.command").execute({ source = "buffers", reveal = true, toggle = true, position = "current" })
  --     end,
  --     desc = "Buffer explorer",
  --   }
  -- },
  -- deactivate = function()
  --   vim.cmd([[Neotree close]])
  -- end,
  -- opts = {
  --   close_if_last_window = true, -- Close Neo-tree if it is the last window float in the tab
  --   popup_border_style = "rounded",
  --   enable_diagnostic = true,
  --   sources = { "filesystem", "buffers", "git_status", "document_symbols" },
  --   open_files_do_not_replace_types = { "terminal", "Trouble", "trouble", "qf", "Outline" },
  --   window = {
  --     position = "current",
  --     mappings = {
  --       ["<space>"] = "none",
  --       ['oa'] = "avante_add_files"
  --     },
  --   },
  --   filesystem = {
  --     hijack_netrw_behavior = "open_default",
  --     follow_current_file = { enabled = true },
  --     use_libuv_file_watcher = true,
  --     filtered_items = {
  --       visible = true,
  --       show_hidden_count = true,
  --       hide_dotfiles = false,
  --       hide_gitignored = true,
  --       hide_by_name = {},
  --       never_show = {
  --         ".git",
  --         ".DS_Store",
  --         "thumbs.db",
  --       },
  --     },
  --     commands = {
  --       avante_add_files = function(state)
  --         local node = state.tree:get_node()
  --         local filepath = node:get_id()
  --         local relative_path = require('avante.utils').relative_path(filepath)
  --
  --         local sidebar = require('avante').get()
  --
  --         local open = sidebar:is_open()
  --         -- ensure avante sidebar is open
  --         if not open then
  --           require('avante.api').ask()
  --           sidebar = require('avante').get()
  --         end
  --
  --         sidebar.file_selector:add_selected_file(relative_path)
  --
  --         -- remove neo tree buffer
  --         if not open then
  --           sidebar.file_selector:remove_selected_file('neo-tree filesystem [1]')
  --         end
  --       end,
  --     }
  --   },
  --   default_component_configs = {
  --     symlink_target = {
  --       enabled = true,
  --     },
  --     indent = {
  --       with_expanders = true, -- if nil and file nesting is enabled, will enable expanders
  --       expander_collapsed = "",
  --       expander_expanded = "",
  --       expander_highlight = "NeoTreeExpander",
  --     },
  --     file_size = {
  --       enabled = false,
  --       required_width = 64, -- min width of window required to show this column
  --     },
  --     type = {
  --       enabled = false,
  --       required_width = 122, -- min width of window required to show this column
  --     },
  --     last_modified = {
  --       enabled = false,
  --       required_width = 88, -- min width of window required to show this column
  --     },
  --     created = {
  --       enabled = false,
  --       required_width = 110, -- min width of window required to show this column
  --     },
  --   },
  -- },
  -- config = function(_, opts)
  --   require("neo-tree").setup(opts)
  --   vim.api.nvim_create_autocmd("TermClose", {
  --     pattern = "*lazygit",
  --     callback = function()
  --       if package.loaded["neo-tree.sources.git_status"] then
  --         require("neo-tree.sources.git_status").refresh()
  --       end
  --     end,
  --   })
  -- end,
}
